# Generated by Django 6.0.7 on 2026-07-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Which attempt this is (1-based)', verbose_name='Attempt Number')),
                ('status', models.CharField(choices=[('success', 'Delivered Successfully'), ('failed', 'Failed'), ('reattempt_scheduled', 'Reattempt Scheduled')], db_index=True, default='failed', max_length=30, verbose_name='Status')),
                ('failure_reason', models.CharField(blank=True, choices=[('customer_unavailable', 'Customer Unavailable'), ('wrong_address', 'Wrong Address'), ('damaged', 'Damaged Parcel'), ('reattempt_required', 'Reattempt Required'), ('other', 'Other')], max_length=30, null=True, verbose_name='Failure Reason')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Attempted At')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this delivery attempt', verbose_name='Notes')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='parcels.parcel', verbose_name='Parcel')),
            ],
            options={
                'verbose_name': 'Delivery Attempt',
                'verbose_name_plural': 'Delivery Attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['parcel', 'status'], name='delivery_de_parcel__10be8e_idx'), models.Index(fields=['attempt_number'], name='delivery_de_attempt_3c15f1_idx'), models.Index(fields=['attempted_at'], name='delivery_de_attempt_72d5fb_idx')],
                'unique_together': {('parcel', 'attempt_number')},
            },
        ),
    ]
