# Generated by Django 6.0.7 on 2026-07-30 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the delivery zone (e.g., 'North Zone')", max_length=100, unique=True, verbose_name='Zone Name')),
                ('pincode_range_start', models.CharField(help_text='Starting pincode of the zone range', max_length=10, verbose_name='Pincode Range Start')),
                ('pincode_range_end', models.CharField(help_text='Ending pincode of the zone range', max_length=10, verbose_name='Pincode Range End')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['pincode_range_start', 'pincode_range_end'], name='parcels_zon_pincode_cbb04e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the parcel (UUID-based)', primary_key=True, serialize=False, verbose_name='Tracking ID')),
                ('sender_name', models.CharField(max_length=200, verbose_name='Sender Name')),
                ('sender_address', models.TextField(verbose_name='Sender Address')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Receiver Name')),
                ('receiver_address', models.TextField(verbose_name='Receiver Address')),
                ('receiver_phone', models.CharField(help_text='Contact phone number of the receiver', max_length=15, verbose_name='Receiver Phone')),
                ('pincode', models.CharField(help_text='Delivery pincode/zip code', max_length=10, verbose_name='Pincode')),
                ('priority', models.CharField(choices=[('express', 'Express'), ('standard', 'Standard')], default='standard', max_length=20, verbose_name='Priority')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the parcel in kilograms', max_digits=8, verbose_name='Weight (kg)')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('sorted', 'Sorted'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reattempt_scheduled', 'Reattempt Scheduled')], db_index=True, default='registered', max_length=30, verbose_name='Status')),
                ('qr_code', models.ImageField(blank=True, help_text='Generated QR code image for this parcel', null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('zone', models.ForeignKey(blank=True, help_text='Delivery zone determined by pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='parcels.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_id'], name='parcels_par_trackin_d26a43_idx'), models.Index(fields=['status'], name='parcels_par_status_469061_idx'), models.Index(fields=['priority'], name='parcels_par_priorit_73d456_idx'), models.Index(fields=['pincode'], name='parcels_par_pincode_a7711b_idx'), models.Index(fields=['zone', 'status'], name='parcels_par_zone_id_d4af80_idx'), models.Index(fields=['created_at'], name='parcels_par_created_456da3_idx')],
            },
        ),
    ]
