# Generated by Django 6.0.7 on 2026-08-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('sorted', 'Sorted'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reattempt_scheduled', 'Reattempt Scheduled')], db_index=True, max_length=30, verbose_name='Status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Changed At')),
                ('notes', models.TextField(blank=True, help_text='Optional context about this status change (e.g. failure reason, attempt number)', verbose_name='Notes')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='parcels.parcel', verbose_name='Parcel')),
                ('rider', models.ForeignKey(blank=True, help_text='Rider associated with this status change (e.g. assignment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_status_entries', to='riders.rider', verbose_name='Rider')),
            ],
            options={
                'verbose_name': 'Parcel Status History',
                'verbose_name_plural': 'Parcel Status History',
                'ordering': ['changed_at'],
                'indexes': [models.Index(fields=['parcel', 'changed_at'], name='parcels_par_parcel__8ff0ed_idx'), models.Index(fields=['status'], name='parcels_par_status_258a43_idx')],
            },
        ),
    ]
