# Generated by Django 6.0.7 on 2026-07-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20, verbose_name='Status')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parcels.parcel', verbose_name='Parcel')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='riders.rider', verbose_name='Rider')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['parcel', 'status'], name='dispatch_as_parcel__837466_idx'), models.Index(fields=['rider', 'status'], name='dispatch_as_rider_i_ff9a16_idx'), models.Index(fields=['assigned_at'], name='dispatch_as_assigne_ebf2e5_idx')],
            },
        ),
    ]
