"""
Seed realistic demo data for presentations.

Run after seed_users so the canonical rider login can be linked to a real
Rider profile:

    python manage.py seed_users
    python manage.py seed_demo_data

Use --reset to clear previously generated demo data first.
"""

from __future__ import annotations

import os
import random
from datetime import timedelta
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.db.models import Count
from django.utils import timezone

try:
    from faker import Faker
except ImportError as exc:  # pragma: no cover - exercised only when dependency is missing
    raise CommandError(
        "Faker is required for seed_demo_data. Install dependencies with "
        "`pip install -r requirements.txt`."
    ) from exc

from accounts.models import UserRole
from delivery.models import AttemptStatus, DeliveryAttempt, FailureReason
from dispatch.models import Assignment, AssignmentStatus
from parcels.models import Parcel, ParcelPriority, ParcelStatus, ParcelStatusHistory, Zone
from riders.models import Rider, VehicleType


User = get_user_model()


DEMO_ZONE_NAMES = [
    "Mumbai Central",
    "Bandra-Kurla Express",
    "Andheri West Hub",
    "Thane Creek Route",
    "Navi Mumbai Logistics",
    "Powai-Tech Corridor",
]
DEMO_USER_PREFIX = "demo_rider_"


class Command(BaseCommand):
    help = "Seed realistic demo zones, riders, parcels, assignments, and delivery attempts."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Clear existing demo data generated by this command before seeding.",
        )
        parser.add_argument(
            "--parcels",
            type=int,
            default=54,
            help="Number of parcels to create (default: 54, clamped between 40 and 60).",
        )
        parser.add_argument(
            "--seed",
            type=int,
            default=20260731,
            help="Random seed for deterministic demo data (default: 20260731).",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        reset = options["reset"]
        parcel_count = max(40, min(60, options["parcels"]))
        random.seed(options["seed"])
        self.fake = Faker("en_IN")
        Faker.seed(options["seed"])

        if reset:
            self._clear_demo_data()
        elif self._demo_data_exists():
            self.stdout.write(
                self.style.WARNING(
                    "Demo data already exists. Skipping. Use --reset to recreate it."
                )
            )
            return

        zones = self._create_zones()
        riders = self._create_riders(zones)
        parcels = self._create_parcels(zones, parcel_count)
        assignments = self._create_assignments(parcels, riders)
        attempts = self._create_delivery_attempts(parcels)
        self._create_status_history(parcels, assignments)
        self._refresh_rider_loads(riders)

        self.stdout.write(self.style.SUCCESS("\nDemo data seeded successfully."))
        self.stdout.write(f"  Zones: {len(zones)}")
        self.stdout.write(f"  Riders: {len(riders)}")
        self.stdout.write(f"  Parcels: {len(parcels)}")
        self.stdout.write(f"  Assignments: {len(assignments)}")
        self.stdout.write(f"  Delivery attempts: {len(attempts)}")
        self.stdout.write(
            self.style.SUCCESS(
                "\nTip: run `python manage.py seed_users` first. The seeded rider login "
                f"({os.environ.get('RIDER_USERNAME', 'rider')}) is linked to one rider profile when available."
            )
        )

    def _demo_data_exists(self) -> bool:
        return (
            Zone.objects.filter(name__in=DEMO_ZONE_NAMES).exists()
            or User.objects.filter(username__startswith=DEMO_USER_PREFIX).exists()
            or Parcel.objects.filter(zone__name__in=DEMO_ZONE_NAMES).exists()
        )

    def _clear_demo_data(self) -> None:
        demo_parcels = Parcel.objects.filter(zone__name__in=DEMO_ZONE_NAMES)
        parcel_count = demo_parcels.count()
        # Assignment and DeliveryAttempt rows cascade from Parcel, but delete explicitly
        # first to make the reset summary and ordering clear.
        DeliveryAttempt.objects.filter(parcel__in=demo_parcels).delete()
        Assignment.objects.filter(parcel__in=demo_parcels).delete()
        ParcelStatusHistory.objects.filter(parcel__in=demo_parcels).delete()
        demo_parcels.delete()

        Rider.objects.filter(user__username__startswith=DEMO_USER_PREFIX).delete()
        User.objects.filter(username__startswith=DEMO_USER_PREFIX).delete()

        rider_username = os.environ.get("RIDER_USERNAME", "rider")
        Rider.objects.filter(user__username=rider_username).delete()

        zones_deleted, _ = Zone.objects.filter(name__in=DEMO_ZONE_NAMES).delete()

        self.stdout.write(
            self.style.WARNING(
                f"Cleared demo data: {parcel_count} parcels and {zones_deleted} zone rows."
            )
        )

    def _create_zones(self) -> list[Zone]:
        zone_specs = [
            ("Mumbai Central", "400001", "400011"),
            ("Bandra-Kurla Express", "400050", "400059"),
            ("Andheri West Hub", "400053", "400061"),
            ("Thane Creek Route", "400601", "400610"),
            ("Navi Mumbai Logistics", "400703", "400710"),
            ("Powai-Tech Corridor", "400076", "400087"),
        ]
        zones = []
        for name, start, end in zone_specs:
            zone, _ = Zone.objects.get_or_create(
                name=name,
                defaults={
                    "pincode_range_start": start,
                    "pincode_range_end": end,
                },
            )
            zones.append(zone)
        return zones

    def _create_riders(self, zones: list[Zone]) -> list[Rider]:
        riders: list[Rider] = []
        vehicle_types = [
            VehicleType.BIKE,
            VehicleType.SCOOTER,
            VehicleType.BIKE,
            VehicleType.VAN,
            VehicleType.CAR,
        ]

        # Link the existing seed_users rider login to one real demo rider profile.
        seeded_rider_username = os.environ.get("RIDER_USERNAME", "rider")
        seeded_rider_user = User.objects.filter(username=seeded_rider_username).first()
        if seeded_rider_user:
            seeded_rider_user.role = UserRole.RIDER
            if not seeded_rider_user.first_name:
                seeded_rider_user.first_name = "Aarav"
            if not seeded_rider_user.last_name:
                seeded_rider_user.last_name = "Sharma"
            seeded_rider_user.phone_number = seeded_rider_user.phone_number or "9876501001"
            seeded_rider_user.save(update_fields=["role", "first_name", "last_name", "phone_number"])
            rider, _ = Rider.objects.get_or_create(
                user=seeded_rider_user,
                defaults={
                    "zone": zones[0],
                    "capacity": 12,
                    "current_load": 0,
                    "is_available": True,
                    "vehicle_type": VehicleType.BIKE,
                },
            )
            riders.append(rider)

        target_count = 18
        first_names = [
            "Vivaan", "Aditya", "Kabir", "Ishaan", "Arjun", "Rohan",
            "Nikhil", "Karan", "Sahil", "Rahul", "Yash", "Dev",
            "Neha", "Priya", "Ananya", "Kavya", "Meera", "Sneha",
        ]
        last_names = [
            "Patel", "Iyer", "Shah", "Mehta", "Rao", "Nair", "Khan",
            "Desai", "Pillai", "Joshi", "Kapoor", "Menon", "Kulkarni",
            "Reddy", "Singh", "Malhotra", "Bose", "Shetty",
        ]

        start_index = 1
        while len(riders) < target_count:
            idx = start_index
            start_index += 1
            username = f"{DEMO_USER_PREFIX}{idx:02d}"
            first_name = first_names[(idx - 1) % len(first_names)]
            last_name = last_names[(idx - 1) % len(last_names)]
            user, created = User.objects.get_or_create(
                username=username,
                defaults={
                    "email": f"{username}@deliveryhub.demo",
                    "first_name": first_name,
                    "last_name": last_name,
                    "role": UserRole.RIDER,
                    "phone_number": f"98765{idx:05d}",
                },
            )
            if created:
                user.set_password("rider123")
                user.save(update_fields=["password"])

            is_unavailable = len(riders) in {5, 13}
            rider, _ = Rider.objects.get_or_create(
                user=user,
                defaults={
                    "zone": zones[len(riders) % len(zones)],
                    "capacity": random.choice([8, 10, 12, 14, 16]),
                    "current_load": 0,
                    "is_available": not is_unavailable,
                    "vehicle_type": vehicle_types[len(riders) % len(vehicle_types)],
                },
            )
            riders.append(rider)
        return riders

    def _create_parcels(self, zones: list[Zone], parcel_count: int) -> list[Parcel]:
        status_mix = (
            [ParcelStatus.REGISTERED] * 7
            + [ParcelStatus.SORTED] * 8
            + [ParcelStatus.ASSIGNED] * 10
            + [ParcelStatus.IN_TRANSIT] * 9
            + [ParcelStatus.DELIVERED] * 13
            + [ParcelStatus.FAILED] * 4
            + [ParcelStatus.REATTEMPT_SCHEDULED] * 3
        )
        while len(status_mix) < parcel_count:
            status_mix.append(random.choice(list(ParcelStatus.values)))
        random.shuffle(status_mix)

        locality_by_zone = {
            "Mumbai Central": ["Marine Lines", "Tardeo", "Byculla", "Girgaon"],
            "Bandra-Kurla Express": ["BKC", "Bandra East", "Kalanagar", "Kurla West"],
            "Andheri West Hub": ["Lokhandwala", "Versova", "DN Nagar", "Oshiwara"],
            "Thane Creek Route": ["Naupada", "Wagle Estate", "Kopri", "Majiwada"],
            "Navi Mumbai Logistics": ["Vashi", "Koparkhairane", "Nerul", "Sanpada"],
            "Powai-Tech Corridor": ["Hiranandani", "Chandivali", "IIT Powai", "Saki Vihar"],
        }

        parcels: list[Parcel] = []
        now = timezone.now()
        for index in range(parcel_count):
            zone = zones[index % len(zones)]
            pincode = str(random.randint(int(zone.pincode_range_start), int(zone.pincode_range_end)))
            status = status_mix[index]
            created_at = now - timedelta(
                days=random.randint(0, 9),
                hours=random.randint(1, 22),
                minutes=random.randint(0, 59),
            )
            locality = random.choice(locality_by_zone[zone.name])
            priority = (
                ParcelPriority.EXPRESS if random.random() < 0.32 else ParcelPriority.STANDARD
            )

            parcel = Parcel.objects.create(
                sender_name=self.fake.name(),
                sender_address=f"{self.fake.building_number()}, {self.fake.street_name()}, {self.fake.city()}",
                receiver_name=self.fake.name(),
                receiver_address=f"Flat {random.randint(101, 2204)}, {self.fake.street_name()}, {locality}, Mumbai",
                receiver_phone=f"9{random.randint(100000000, 999999999)}",
                pincode=pincode,
                zone=zone,
                priority=priority,
                weight=Decimal(str(round(random.uniform(0.25, 18.5), 2))),
                status=status,
            )
            Parcel.objects.filter(pk=parcel.pk).update(
                created_at=created_at,
                updated_at=created_at + timedelta(hours=random.randint(1, 36)),
            )
            parcel.refresh_from_db()
            parcels.append(parcel)
        return parcels

    def _create_assignments(self, parcels: list[Parcel], riders: list[Rider]) -> list[Assignment]:
        assignments: list[Assignment] = []
        assignable_statuses = {
            ParcelStatus.ASSIGNED,
            ParcelStatus.IN_TRANSIT,
            ParcelStatus.DELIVERED,
            ParcelStatus.FAILED,
            ParcelStatus.REATTEMPT_SCHEDULED,
        }
        assignment_status_map = {
            ParcelStatus.ASSIGNED: AssignmentStatus.ASSIGNED,
            ParcelStatus.IN_TRANSIT: AssignmentStatus.IN_TRANSIT,
            ParcelStatus.DELIVERED: AssignmentStatus.DELIVERED,
            ParcelStatus.FAILED: AssignmentStatus.FAILED,
            ParcelStatus.REATTEMPT_SCHEDULED: AssignmentStatus.IN_TRANSIT,
        }
        for parcel in parcels:
            if parcel.status not in assignable_statuses:
                continue
            same_zone_riders = [r for r in riders if r.zone_id == parcel.zone_id]
            rider_pool = same_zone_riders or riders
            rider = random.choice(rider_pool)
            assigned_at = max(
                parcel.created_at + timedelta(hours=random.randint(2, 18)),
                timezone.now() - timedelta(days=10),
            )
            assignment = Assignment.objects.create(
                parcel=parcel,
                rider=rider,
                status=assignment_status_map[parcel.status],
            )
            Assignment.objects.filter(pk=assignment.pk).update(assigned_at=assigned_at)
            assignment.refresh_from_db()
            assignments.append(assignment)
        return assignments

    def _create_delivery_attempts(self, parcels: list[Parcel]) -> list[DeliveryAttempt]:
        attempts: list[DeliveryAttempt] = []
        delivered = [p for p in parcels if p.status == ParcelStatus.DELIVERED]
        failed = [p for p in parcels if p.status == ParcelStatus.FAILED]
        reattempt = [p for p in parcels if p.status == ParcelStatus.REATTEMPT_SCHEDULED]

        # 2-3 visible multi-attempt success sequences.
        multi_success = delivered[:3]
        for parcel in multi_success:
            attempts.extend(
                self._add_attempt_sequence(
                    parcel,
                    [
                        (AttemptStatus.FAILED, FailureReason.CUSTOMER_UNAVAILABLE, "Customer unavailable on first visit."),
                        (AttemptStatus.SUCCESS, None, "Delivered successfully on scheduled reattempt."),
                    ],
                )
            )

        for parcel in delivered[3:]:
            attempts.extend(
                self._add_attempt_sequence(
                    parcel,
                    [(AttemptStatus.SUCCESS, None, "Delivered to customer and OTP verified.")],
                )
            )

        failure_reasons = [
            FailureReason.CUSTOMER_UNAVAILABLE,
            FailureReason.WRONG_ADDRESS,
            FailureReason.DAMAGED,
        ]
        for index, parcel in enumerate(failed):
            reason = failure_reasons[index % len(failure_reasons)]
            attempts.extend(
                self._add_attempt_sequence(
                    parcel,
                    [
                        (AttemptStatus.FAILED, reason, self._notes_for_reason(reason, attempt=1)),
                        (AttemptStatus.FAILED, reason, self._notes_for_reason(reason, attempt=2)),
                        (AttemptStatus.FAILED, reason, self._notes_for_reason(reason, attempt=3)),
                    ],
                )
            )

        for index, parcel in enumerate(reattempt):
            reason = failure_reasons[index % len(failure_reasons)]
            attempts.extend(
                self._add_attempt_sequence(
                    parcel,
                    [
                        (AttemptStatus.FAILED, reason, self._notes_for_reason(reason, attempt=1)),
                    ],
                )
            )
        return attempts

    def _add_attempt_sequence(
        self,
        parcel: Parcel,
        sequence: list[tuple[str, str | None, str]],
    ) -> list[DeliveryAttempt]:
        attempts: list[DeliveryAttempt] = []
        base_time = parcel.created_at + timedelta(days=random.randint(1, 3), hours=random.randint(2, 8))
        for attempt_number, (status, reason, notes) in enumerate(sequence, start=1):
            attempted_at = base_time + timedelta(days=attempt_number - 1, hours=random.randint(1, 5))
            attempt = DeliveryAttempt.objects.create(
                parcel=parcel,
                attempt_number=attempt_number,
                status=status,
                failure_reason=reason,
                notes=notes,
            )
            DeliveryAttempt.objects.filter(pk=attempt.pk).update(attempted_at=attempted_at)
            attempts.append(attempt)
        latest_time = max(a.attempted_at for a in DeliveryAttempt.objects.filter(parcel=parcel))
        Parcel.objects.filter(pk=parcel.pk).update(updated_at=latest_time)
        return attempts

    def _notes_for_reason(self, reason: str, attempt: int) -> str:
        if reason == FailureReason.CUSTOMER_UNAVAILABLE:
            return f"Attempt {attempt}: customer unavailable; reattempt coordinated by support."
        if reason == FailureReason.WRONG_ADDRESS:
            return f"Attempt {attempt}: address could not be verified with receiver."
        if reason == FailureReason.DAMAGED:
            return f"Attempt {attempt}: parcel marked damaged during delivery scan."
        return f"Attempt {attempt}: delivery exception recorded."

    def _create_status_history(
        self, parcels: list[Parcel], assignments: list[Assignment]
    ) -> None:
        """Create status history entries for seeded parcels so the timeline has data."""
        assignment_by_parcel = {a.parcel_id: a for a in assignments}

        for parcel in parcels:
            # Always record 'registered' as the initial state
            ParcelStatusHistory.objects.create(
                parcel=parcel,
                status=ParcelStatus.REGISTERED,
                changed_at=parcel.created_at,
                notes="Parcel registered via intake",
            )

            # If the parcel has an assignment, record the assigned state
            assignment = assignment_by_parcel.get(parcel.pk)
            if assignment:
                ParcelStatusHistory.objects.create(
                    parcel=parcel,
                    status=ParcelStatus.ASSIGNED,
                    changed_at=assignment.assigned_at,
                    notes=f"Assigned to {assignment.rider}",
                    rider=assignment.rider,
                )

            # Record the current status as the latest entry
            if parcel.status not in (ParcelStatus.REGISTERED, ParcelStatus.ASSIGNED):
                ParcelStatusHistory.objects.create(
                    parcel=parcel,
                    status=parcel.status,
                    changed_at=parcel.updated_at,
                    notes=f"Status updated to {parcel.get_status_display()}",
                )

    def _refresh_rider_loads(self, riders: list[Rider]) -> None:
        active_counts = (
            Assignment.objects.filter(
                rider__in=riders,
                status__in=[AssignmentStatus.ASSIGNED, AssignmentStatus.IN_TRANSIT],
            )
            .values("rider")
            .annotate(count=Count("id"))
        )
        counts = {item["rider"]: item["count"] for item in active_counts}
        for rider in riders:
            Rider.objects.filter(pk=rider.pk).update(
                current_load=min(counts.get(rider.pk, 0), rider.capacity)
            )