# Generated by Django 6.0.7 on 2026-07-30 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Maximum number of parcels this rider can carry per day', verbose_name='Max Capacity')),
                ('current_load', models.PositiveIntegerField(default=0, help_text='Number of parcels currently assigned to this rider', verbose_name='Current Load')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this rider is currently available for assignments', verbose_name='Is Available')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck'), ('on_foot', 'On Foot')], default='bike', max_length=20, verbose_name='Vehicle Type')),
                ('user', models.OneToOneField(help_text='Linked user account for this rider', on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('zone', models.ForeignKey(blank=True, help_text='Primary delivery zone for this rider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='parcels.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Rider',
                'verbose_name_plural': 'Riders',
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['is_available'], name='riders_ride_is_avai_e66f19_idx'), models.Index(fields=['zone', 'is_available'], name='riders_ride_zone_id_1fd0aa_idx'), models.Index(fields=['capacity'], name='riders_ride_capacit_9ada66_idx')],
            },
        ),
    ]
